filters/filter.go, filters/filter_test.go, filters/mock_filter.go, policy/policy.go, policy/policy_benchmark_test.go, policy/policy_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/base_iterator.go, protocol/msgpack/raw_metric_test.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go, rules/rule.go, rules/rule_test.go
Summary: Refactoring filters and rules out of policy package
Test Plan: Unit
Reviewers: xichen2020
Subscribers:
Revert Plan:
=> Refactor filters and rules out of policy package

filters/filter.go, filters/filter_test.go
=> Add negation filter

filters/filter.go, filters/filter_benchmark_test.go, filters/filter_test.go
=> Add glob matching to filters

filters/filter.go, filters/filter_benchmark_test.go, filters/filter_test.go
=> Add multi-char range filters and multi-select single range filters

rules/rollup.go
=> Search rollups backwards

glide.lock, glide.yaml, policy/policy.go, policy/policy_test.go, policy/resolution.go, policy/resolution_test.go
This PR adds utility functions to parse policy and resolution from input strings.
=> Add utility functions to parse policy and resolution

policy/aggregation_type.go, policy/aggregation_type_test.go
=> Indicate Whether quantile slice is from pool

policy/aggregation_type.go, policy/aggregation_type_test.go
=> YAML unmarshal aggregation types

policy/aggregation_id_compress.go, policy/aggregation_id_compress_test.go
=> Shortcut aggregation id decompression

policy/aggregation_id_compress.go, policy/aggregation_id_compress_test.go, policy/aggregation_type.go, policy/aggregation_type_pool_test.go, policy/aggregation_type_test.go
=> Expose the id of aggregation types

policy/aggregation_type.go, policy/policy.go, policy/policy_test.go, policy/retention.go, policy/retention_test.go, policy/storage_policy.go
=> Add functions to convert policy into schema

policy/aggregation_type.go, policy/aggregation_type_test.go
=> YAML Unmarshal aggregation type

matcher/cache/cache_test.go, matcher/cache/list_test.go, matcher/match_test.go, rules/result.go, rules/result_test.go, rules/ruleset.go, rules/ruleset_test.go
This PR exposes the version of the ruleset that generates the match result.
=> Expose the version of the match result

metric/id/m3/id.go, metric/id/m3/id_test.go
=> Change interface of m3.IsRollupID to fit better with id.MatchIDFn

matcher/config.go, matcher/config_test.go, rules/ruleset.go, rules/ruleset_test.go
=> Add match mode to config

policy/storage_policy.go, policy/storage_policy_test.go, protocol/msgpack/base_iterator.go, protocol/msgpack/raw_metric_test.go
cc @cw9 
This PR adds `MustParsePolicy` utility function.
=> Add MustParsePolicy()

filters/filter.go, filters/filter_benchmark_test.go, filters/tags_filter.go, rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/namespace_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go
Adding deep copy logic.
Also, renamed newNameSpace to newNamespace
=> Deep clone functions for rules and namespaces 

glide.lock, glide.yaml, matcher/cache/cache.go, matcher/cache/cache_test.go, matcher/cache/list.go, matcher/cache/list_test.go, matcher/namespaces.go, matcher/namespaces_test.go, policy/policy_benchmark_test.go, policy/policy_test.go, policy/resolution.go, policy/resolution_test.go, policy/staged_policy_test.go, policy/storage_policy.go, policy/storage_policy_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_iterator.go, protocol/msgpack/base_test.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go, rules/mapping_test.go, rules/result_test.go, rules/rollup_test.go, rules/ruleset_test.go
This PR updates the versions of m3x and m3cluster and fixes and updates any imports accordingly.
=> [glide] Update m3x and m3cluster dependencies

matcher/ruleset_test.go, rules/mapping.go, rules/mapping_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go
- Add Mutators now return the new id they created
- History slices are sorted most recent first
=> ctl interface improvements

rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/namespace_test.go, rules/rollup.go, rules/rollup_test.go
- Adding the tombstoned flag to views
- Namespaces now uses the view pattern used by rules
=> Tombstoned in Views + Namespace Views

glide.lock, matcher/ruleset_test.go, metric/types.go, policy/aggregation_type.go, rules/errors.go, rules/ruleset.go, rules/ruleset_test.go, rules/validator.go, rules/validator_options.go, rules/validator_test.go
cc @dgromov @prateek @cw9 
This PR adds validation logic when mutating rulesets through the `Validator` interface.
=> Add Ruleset Validation Logic

glide.lock, glide.yaml, policy/retention_test.go
This PR pulls in latest m3x into m3metrics.
=> Update m3x dependency

policy/aggregation_id_compress_test.go, policy/aggregation_type.go, policy/aggregation_type_options.go, policy/aggregation_type_options_test.go, rules/ruleset_test.go
=>  Add methods to look up aggregation type by suffix

rules/validator_test.go
Adds policies to test fixtures to make sure tests don't fail
=> Updates validation tests

glide.lock, glide.yaml
=> Pull logger change in kv

metric/types.go, metric/types_test.go
To be reused in the load gen tool
@xichen2020
=> Extract ParseType function to be reused

glide.lock, glide.yaml
cc @cw9 
Update m3cluster SHA to tip of master.
=> Update m3cluster dependency

rules/validator_config_test.go
This PR adds tests for validator configuration.
=> Add validator config tests

glide.lock, glide.yaml, rules/ruleset_test.go
=> Pull latest m3x/m3cluster

rules/models/changes/mapping.go, rules/models/changes/mapping_test.go, rules/models/changes/op.go, rules/models/changes/rollup.go, rules/models/changes/rollup_test.go, rules/models/changes/ruleset.go, rules/models/changes/ruleset_test.go
This PR adds common changes structs to describe changes to rulesets.
=> Add changes structs

matcher/match_test.go, matcher/namespaces.go, matcher/namespaces_test.go, matcher/ruleset.go, matcher/ruleset_test.go, policy/policy.go, policy/resolution.go, policy/retention.go, policy/storage_policy.go, policy/storage_policy_test.go, rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/namespace_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go, rules/store/kv/store.go, rules/store/kv/store_test.go, rules/validator/validator_test.go
cc @cw9 
This PR removes the import alias `schema`.
=> Remove import alias

aggregation/id.go, aggregation/type.go, metadata/metadata.go, metadata/metadata_test.go, op/applied/type.go, op/applied/type_test.go, op/type.go, op/type_test.go, policy/storage_policy.go
cc @cw9 
This replays PR #140 onto master.
=> Add metric and pipeline metadata

op/applied/type.go, op/applied/type_test.go
This replays PR #143 onto master.
=> More flexible SubPipeline API (#143)

aggregation/id_compress.go, aggregation/id_compress_test.go, metadata/metadata.go, metadata/metadata_test.go, metric/unaggregated/types.go
This replays #146 onto master.
=> Add a few auxiliary functions and type definitions (#146)

encoding/migration/convert.go, encoding/migration/convert_test.go, encoding/migration/unaggregated_iterator.go, encoding/migration/unaggregated_iterator_test.go, encoding/protobuf/unaggregated_encoder.go, encoding/protobuf/unaggregated_encoder_test.go, encoding/protobuf/unaggregated_iterator.go, encoding/protobuf/unaggregated_iterator_test.go, encoding/types.go
cc @cw9 
This replays #150 onto master.
=> Add migration decoder (#150)

generated-source-files.mk, matcher/match_test.go, matcher/namespaces.go, matcher/namespaces_test.go, matcher/ruleset.go, matcher/ruleset_test.go, policy/policy.go, policy/resolution.go, policy/retention.go, policy/storage_policy.go, policy/storage_policy_test.go, rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/namespace_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go, rules/store/kv/store.go, rules/store/kv/store_test.go, rules/validator/validator_test.go
This PR replays #153 onto master.
=> Remove import alias (#153)

encoding/protobuf/buffer.go, encoding/protobuf/buffer_test.go, encoding/protobuf/unaggregated_encoder.go, encoding/protobuf/unaggregated_encoder_test.go, metric/unaggregated/types.go, metric/unaggregated/types_test.go
cc @cw9 
This replays #154 onto master
=> Add a few utility methods (#154)

encoding/migration/convert.go, encoding/migration/convert_test.go
This PR exports the API that converts from legacy policies list to staged metadatas.
=> Export conversion API

rules/models/mapping.go
=> Use aggregation as the JSON tag for aggregation id

aggregation/type_config.go, aggregation/type_config_test.go, aggregation/types_options.go, aggregation/types_options_test.go
This PR simplifies the aggregation type options with smaller interface.
=> Simplify type options with smaller interface

rules/active_ruleset.go, rules/active_ruleset_test.go
This PR adds logic to ensure the cutover times of staged metadatas produced by mapping rule matches are always non decreasing.
=> Ensure cutover times of staged metadatas from mapping rule matches are non-decreasing
