metric/aggregated/types.go, metric/unaggregated/types.go, protocol/msgpack/aggregated_encoder.go, protocol/msgpack/aggregated_encoder_test.go, protocol/msgpack/aggregated_iterator.go, protocol/msgpack/aggregated_iterator_pool.go, protocol/msgpack/aggregated_iterator_pool_test.go, protocol/msgpack/aggregated_iterator_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/base_iterator.go, protocol/msgpack/buffered_encoder.go, protocol/msgpack/buffered_encoder_pool_test.go, protocol/msgpack/buffered_encoder_test.go, protocol/msgpack/options.go, protocol/msgpack/raw_metric.go, protocol/msgpack/raw_metric_test.go, protocol/msgpack/schema.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_pool.go, protocol/msgpack/unaggregated_iterator_pool_test.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go, protocol/msgpack/wire_format.md
cc @robskillington @kobolog @martin-mao @cw9 
This PR adds the message-backed encoder and decoder for aggregated metrics. 
Since the encoders / iterators for unaggregated metrics and aggregated metrics share a lot of common low-level encoding/decoding functions, I factored them out into base interfaces shared by both encoders / iterators.
=> MessagePack encoder and decoder for aggregated metrics

policy/policy.go, policy/types.go, protocol/msgpack/aggregated_encoder_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/base_iterator.go, protocol/msgpack/schema.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go, protocol/msgpack/wire_format.md
cc @robskillington @kobolog @cw9 @martin-mao 
Also use the `EncodeTime` API provided by msgpack to encode time for space savings.
=> Encode cutover time for versioned policies

policy/policy.go, protocol/msgpack/aggregated_iterator.go, protocol/msgpack/base_iterator.go, protocol/msgpack/unaggregated_iterator.go
cc @kobolog @cw9 @robskillington 
This PR clears the iterator fields before putting them back into pools to avoid pooled objects holding references to large amount of memory, causing a memory leak
=> Clear iterators before putting them back into pools

protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/raw_metric.go, protocol/msgpack/raw_metric_test.go
cc @kobolog @cw9 @robskillington 
This PR fixes a bug where the ID for the raw metric used to point to the internal buffer instead of the raw data slice, which causes issues when the same iterator is reused to decode multiple metrics.
=> Decoded raw metric ID should be part of raw data slice

glide.lock, glide.yaml, metric/aggregated/types.go, metric/common.go, protocol/msgpack/aggregated_encoder.go, protocol/msgpack/aggregated_encoder_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_roundtrip_test.go
cc @kobolog @cw9 @robskillington 
This PR adds support for encoding metrics with chunked ids efficiently.
The main use case this PR addresses is to encode metrics in the aggregation tier before they are flushed downstream. Each metric id usually has a prefix (e.g., stats.blah), a body (i.e., the main id), and a suffix (e.g., .p99). Since the current encoder API only handles single-byte-slice ids, this requires either merging the prefix/body/suffix before encoding each id, which costs extra time due to extra byte copies, or storing the precomputed full ids for each metric, which costs extra space (e.g., each timer id would need to be stored as 10+ different ids due to different suffixes). Neither of which is optimal due to the large number of encoding operations in the aggregation tier. …
=> Support encoding metrics with chunked IDs efficiently

policy/policy.go, policy/policy_test.go, protocol/msgpack/schema.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go
This PR addresses an issue where we used to use the policy version to determine whether the policies are the default policies (in particular, if the version is 0, we consider it as default, and non-default otherwise). This however means if we mark the policy as the default when the rules for a namespace are deleted, the policy version will be 0 regardless of what the actual policy version is, causing the aggregation tier to ignore such policies.
This PR introduces the `isDefault` and `policies` field in the `VersionedPolicies` object so we can explicitly mark policies as default while respecting the actual policy version.
=> Explicitly mark versioned policies as default if needed

protocol/msgpack/aggregated_iterator_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/buffered_encoder.go, protocol/msgpack/buffered_encoder_pool_test.go, protocol/msgpack/buffered_encoder_test.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_iterator_test.go
cc @robskillington @prateek @ben-lerner @cw9 
This PR adds the `Buffer` and the `Encoder` interface to conceptually separate the byte buffering operations and the encoding operations for better separation of concerns.
=> Add Buffer and Encoder interface for better separation of concerns

rules/options.go, rules/rule.go, rules/rule_test.go
This PR stores the ID of the rollup metrics in the match result to avoid repeatedly recomputing the id from the name and the tags in the rollup targets, saving significant CPU time and reducing memory allocations.
=> Add rollup metric ID to match result

rules/mapping.go, rules/mapping_test.go
Rules are stored by cutover time ascending, searching backwards should
be faster
@xichen2020 @robskillington @jeromefroe
=> Search rules backwards

metric/unaggregated/types.go, protocol/msgpack/aggregated_iterator.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_iterator.go, protocol/msgpack/buffered_encoder_test.go, protocol/msgpack/options.go, protocol/msgpack/raw_metric.go, protocol/msgpack/raw_metric_test.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_pool.go, protocol/msgpack/unaggregated_iterator_pool_test.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go
cc @jeromefroe @cw9 @martin-mao 
This PR adds many improvements in terms of perf and memory / GC efficiency for the unaggregated iterator, given the observation that the decoded value is always processed before the next value is decoded. The notable improvements include:
* The unaggregated iterator used to always allocate a new byte slice for decoded metric ids. It now has an internal byte slice that caches the decoded metric id and does zero copy when reading off the wire. This reduces memory / GC overhead and improves performance.
* The unaggregated iterator used to always allocate a policy slice for decoded policies. It now has an internal policy slice that caches the decoded policies.
* The unaggregated iterator used to always allocate a float64 slice for decoded timer values. It now …
=> Cache id and policies and buffer timer values when decoding unaggregated metrics

metric/aggregated/types.go, metric/unaggregated/types.go, policy/policy.go, policy/policy_benchmark_test.go, policy/policy_test.go, protocol/msgpack/aggregated_encoder.go, protocol/msgpack/aggregated_encoder_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/base_iterator.go, protocol/msgpack/raw_metric.go, protocol/msgpack/raw_metric_test.go, protocol/msgpack/schema.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go, protocol/msgpack/wire_format.md, rules/mapping.go, rules/mapping_test.go, rules/result.go, rules/result_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go
cc @jeromefroe @cw9 @robskillington @martin-mao @prateek 
This PR adds APIs to match an id against rules for a given time range, in which case the match result may contain more than one policies matched at different times within the time range. The main use case here is to handle clock skews between the collector and the aggregation tier. Specifically when collector matches metric IDs against rules at time T, it finds the matching result within [T-Tcs, T+Tcs) where Tcs is the max clock skew across all collectors, sends the match result to the aggregation tier, and let the aggregation tier decide which policies it should use since the aggregation tier's clock is considered the source of truth.
As a result, the PR also adds APIs to msgpack encode a list of staged policies and send that …
=> Provide APIs to match multiple policies within a time range and send multiple policies across network

protocol/msgpack/types.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_encoder_test.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_test.go, protocol/msgpack/unaggregated_roundtrip_test.go
cc @robskillington @cw9 @jeromefroe @prateek 
This PR adds APIs to encode and decode metrics without policies so we can batch encode values sent from prod collectors to proxy collectors.
=> Add APIs to encode / decode metrics without policies

filters/filter_benchmark_test.go, filters/mock_filter.go, filters/tags_filter.go, filters/tags_filter_test.go, glide.lock, glide.yaml, metric/aggregated/types.go, metric/id/id.go, metric/id/m3/id.go, metric/id/m3/id_test.go, metric/id/tag.go, metric/id/tag_test.go, metric/unaggregated/types.go, protocol/msgpack/aggregated_encoder.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/base_encoder.go, protocol/msgpack/base_iterator.go, protocol/msgpack/raw_metric.go, protocol/msgpack/raw_metric_test.go, protocol/msgpack/types.go, protocol/msgpack/unaggregated_encoder.go, protocol/msgpack/unaggregated_iterator.go, protocol/msgpack/unaggregated_iterator_test.go, rules/mapping.go, rules/mapping_test.go, rules/options.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go
cc @robskillington @cw9 @jeromefroe @prateek @martin-mao 
This PR moves the `ID` interface from m3collector to m3metrics so it can be shared across repos. It also adds the implementation and utility functions for M3 metrics, which will be used from collectors.
=> Move ID interface to m3metrics and add m3 id implementation

rules/result.go, rules/result_test.go, rules/ruleset_test.go
This PR modifies the RollupAt API to determine whether a rollup metric has been tombstoned. It also changed a few time-related APIs to pass in nanoseconds instead of time.Time so they are more consistent across the codebase.
=> Modify RollupAt API to determine whether a rollup metric has been tombstoned

rules/ruleset.go, rules/ruleset_test.go
This PR adds logic to match tombstoned rules to determine cutover time of the resolved policies.
=> Match tombstoned rules to determine cutover time

metric/id/id.go, metric/id/m3/id.go, metric/id/m3/id_test.go, rules/options.go, rules/ruleset.go, rules/ruleset_test.go
This PR adapts the `MatchAll` interface to find policies for rollup metrics (i.e., those generated from a rollup rule).
=> Add functions to find mapping policies for rollup metrics

rules/ruleset.go, rules/ruleset_test.go
cc @cw9 @prateek 
This PR rename match modes `Forward` and `Reverse` to `ForwardMatch` and `ReverseMatch`.
=> Rename match modes

glide.lock, glide.yaml, matcher/cache.go, matcher/cache/cache.go, matcher/cache/cache_test.go, matcher/cache/list.go, matcher/cache/list_test.go, matcher/cache/options.go, matcher/match.go, matcher/match_test.go, matcher/namespaces.go, matcher/namespaces_test.go, matcher/options.go, matcher/ruleset.go, matcher/ruleset_test.go
This PR moves the rule matcher API from `m3collector` to `m3metrics` so the underlying implementation can be reused across the collector, the indexer, and the query service, with some modifications to the existing implementation.
* Define `Namespaces` interface and `RuleSet` interface. They are useful for indexer/query where in-memory caching is ineffective and we'd like to bypass the readthrough cache and directly perform rule matching using the underlying namespaces and rulesets.
* I also adapted the `Matcher` interface to take a `fromNanos` and a `toNanos` as the match time range. This used to be determined internally inside the `cache` implementation and various other places based on the clock skew offsets. By explicitly passing in the time range, it can …
=> Rule matcher API

policy/policy.go, policy/staged_policy.go, policy/staged_policy_test.go
This PR adds logic to perform JSON marshalling/unmarshaling of a list of policies.
=> JSON marshaling of policies list

matcher/cache/config.go, matcher/cache/config_test.go, matcher/cache/options.go, matcher/config.go, matcher/config_test.go, matcher/match.go, matcher/namespaces.go, metric/id/m3/id.go, metric/id/m3/id_test.go
Move configs from statsdex so it can be reused in proxy collector and query.
Change IsRollupID to take in an iterator pool in order to make the function thread safe. It will be reusing the pool in the tags filter.
@xichen2020
=> Add configurations

metric/id/m3/id.go, metric/id/m3/id_test.go
This PR generalizes `NameAndTags` slightly so it can handle M3 ids both before and after aggregation.
=> Slightly generalize NameAndTags for m3 ids

matcher/config.go, matcher/match_test.go, matcher/namespaces.go, matcher/namespaces_test.go, matcher/options.go, matcher/ruleset.go, matcher/ruleset_test.go, rules/ruleset.go, rules/ruleset_test.go
This PR adds `MatchRangePast` to the matcher configuration. It also uses `time.MaxInt64` as the default value for `MatchRangePast`, which means there is no lower bound on the match range by default.
=> Add MatchRangePast to config

matcher/ruleset_test.go, policy/aggregation_type.go, policy/policy_test.go, rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/namespace_test.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go
Allow converting m3metrics/rules structures into their kv schema counterparts.
=> Rule objects to schema

protocol/msgpack/buffered_encoder_pool.go, protocol/msgpack/buffered_encoder_pool_test.go, protocol/msgpack/options.go, protocol/msgpack/types.go
This PR adds a maximum capacity check to the buffered encoder pool. When set, buffers with a capacity greater than the maximum capacity will not be returned to the pool. This PR is to address memory growth in the proxycollectors when they receive large timer batches, write them into a single buffer, and return that buffer to the pool.
cc @xichen2020
=> [buffered encoder pool] Add maximum capacity check to buffers returned to pool

protocol/msgpack/buffered_encoder_pool.go
We should check for options being `nil` so callers can pass `nil` to express that they want to use the default options.
cc @xichen2020
=> [buffered encoder pool] Check if options are nil

filters/filter_benchmark_test.go
Had been meaning to put up a really short PR to fix these for a while, finally got around to it: `s/Equity/Equality`.
=> [filters] Fix typo in equality filter benchmarks

.travis.yml, filters/filter_benchmark_test.go, matcher/ruleset_test.go
This PR adds Go 1.8 and 1.9 to the versions of Go we test against in Travis.
In addition, it seems the `unparam` linter has been updated and caught some new cases, so this PR also addresses the new issues found by it.
=> [travis] Add go 1.8 and 1.9 to travis tests

protocol/msgpack/aggregated_encoder.go, protocol/msgpack/aggregated_encoder_test.go, protocol/msgpack/aggregated_iterator.go, protocol/msgpack/aggregated_iterator_test.go, protocol/msgpack/aggregated_roundtrip_test.go, protocol/msgpack/schema.go, protocol/msgpack/types.go
This PR adds two new APIs to support including encoding time when encoding metrics and policies. Such encoding time will be used to compute e2e latencies (e.g., prior to ingest etc).
=> Aggregated encoder supports including encoding time in encoded data

glide.lock, glide.yaml, matcher/config.go, matcher/config_test.go
=> Use kv configuration from m3cluster

metric/types.go, rules/validator.go, rules/validator_options.go, rules/validator_test.go
cc @dgromov 
This PR generalizes the metric types function a little to return a slice of types instead of just a single type. This is to handle the edge case where the users don't have a type tag or have a regex matching multiple metric types in the metric filter.
=> Generalize metric types function to return a slice of types

metric/types.go, metric/types_test.go, rules/store.go, rules/store_test.go, rules/validator.go, rules/validator_options.go, rules/validator_test.go
cc @dgromov @cw9 @jeromefroe 
This PR changes the `MetricTypeFn` to return an error and validates the metric types to bail early if no metric type can be matched by the rule.
=> Validate metric types

glide.lock, glide.yaml, policy/policy_test.go, policy/resolution.go, policy/resolution_test.go, policy/retention.go, policy/retention_test.go, policy/staged_policy_test.go, policy/storage_policy.go, policy/storage_policy_test.go
cc @cw9 @jeromefroe @dgromov 
This PR makes the string representation of storage policies more user friendly for better UI experience. In particular, if the precision of the resolution is the default precision, it's not written as part of the string.
=> More user-friendly string representation of storage policies

matcher/cache/cache.go, matcher/cache/cache_test.go, matcher/config.go, matcher/config_test.go, matcher/match.go, matcher/match_test.go, matcher/namespaces.go, matcher/namespaces_test.go, matcher/options.go, matcher/ruleset.go, matcher/ruleset_test.go, policy/aggregation_type.go, policy/aggregation_type_config.go, policy/aggregation_type_config_test.go, policy/aggregation_type_test.go, policy/config.go, policy/config_test.go, policy/options.go, policy/policy.go, policy/policy_test.go, policy/staged_policy.go, policy/staged_policy_test.go, rules/options.go, rules/ruleset.go, rules/ruleset_test.go
We need to check aggregation type specifically because we support policies with different aggregation types, so we can't simply match by id in this case.
Major changes in this diff:
* Add ForwardMatch() and ReverseMatch() methods to ruleset.Matcher and matcher.Namespace interface.
* Removed MatchMode.
* Moved config and options from aggregator repo to setup default aggregation types for different metric type.
* Logic to filter policies based on aggregation type and metric type.
* Fixed a bug in mergeMappingResults() where the initial mappingResults maybe empty.
@xichen2020 @jeromefroe
=> Support aggregation type filtering in ReverseMatch

rules/mapping.go, rules/rollup.go, rules/ruleset.go, rules/ruleset_test.go
This PR ensures we do not process policies or rollup targets of tombstoned rule snapshots during both forward matching and reverse matching.
=> Do not process policies or rollup targets of tombstoned rule snapshots

matcher/config.go, policy/aggregation_type_config.go, policy/aggregation_type_config_test.go, policy/aggregation_type_options.go, policy/aggregation_type_options_test.go
So that we only need to override the config in m3aggregator and directly use defaults in query and indexer
@xichen2020
=> Replace suffixes with type strings

rules/validator.go, rules/validator_options.go, rules/validator_test.go
This PR adds logic to optionally enforce a list of required rollup tags during validation.
=> Provide options to enforce required rollup tags

rules/validator.go, rules/validator_options.go, rules/validator_test.go
Adds to validator_options as well. Wasn't sure whether to call RollupTargetName or RollupMetricName
=> Adds invalid char validators for rollup tags and target names

.metalinter.json, policy/aggregation_id_compress.go, policy/aggregation_type.go, policy/aggregation_type_config.go, policy/aggregation_type_test.go, policy/policy.go, policy/policy_test.go, rules/ruleset.go, rules/ruleset_test.go
cc @cw9 @jeromefroe
This PR relaxes the constraint for policy resolution to allow policies to have same resolution but with different retention periods. As such, when querying an id for 3-day data with a layered policy list with [1m:2d, 1m:40d], the policy resolver could use the 1m:2d for the first two days and the 1m:40d for data older than 2 days in case the data in the 1m:40d is lagging behind the 1m:2d data during the migration phase.
=> Allow policies to have same resolution with different retentions

policy/staged_policy.go, policy/staged_policy_test.go, rules/ruleset.go
This PR renames `SamePolicies` to `Equals` and perform stricter checks for equality semantics.
=> Stricter check to compare staged policies

matcher/config.go
cc @cw9 
This PR removes options validation since it's already done inside m3cluster.
=> Remove options validation since it's done inside m3cluster

rules/rollup.go, rules/rollup_test.go, rules/validator.go, rules/validator_config.go, rules/validator_test.go
This PR adds configuration for the validator to be reused by both `m3ctl` and internal tooling. It also adds a new `ValidateSnapshot` API to validate a rule snapshot and additional validation logic to detect duplicate rollup tags and policies.
=> Add validator configuration and export `ValidateSnapshot`

glide.lock, rules/store.go, rules/store/kv/store.go, rules/store/kv/store_test.go, rules/validator/config.go, rules/validator/config_test.go, rules/validator/namespace/kv/config.go, rules/validator/namespace/kv/config_test.go, rules/validator/namespace/kv/options.go, rules/validator/namespace/kv/validator.go, rules/validator/namespace/kv/validator_test.go, rules/validator/namespace/static/config.go, rules/validator/namespace/static/validator.go, rules/validator/namespace/static/validator_test.go, rules/validator/namespace/validator.go, rules/validator/options.go, rules/validator/validator.go, rules/validator/validator_test.go
This PR adds namespace validation logic to validate the namespace associated with a ruleset to prevent invalid namespaces from being persisted.
=> Add namespace validation logic

rules/namespace.go, rules/namespace_test.go
This PR fixes a bug in setting the ruleset version when reviving a namespace. Specifically, when a pre-existing namespace is revived, the ruleset version in the namespace snapshot should be one after the tombstoned ruleset version.
=> Set correct ruleset version when reviving a namespace

errors/errors.go, filters/tags_filter.go, filters/tags_filter_test.go, rules/mapping.go, rules/mapping_test.go, rules/namespace.go, rules/rollup.go, rules/rollup_test.go, rules/ruleset.go, rules/ruleset_test.go, rules/validator/validator.go, rules/validator/validator_test.go
This PR adds filter validation when constructing mapping rule and rollup rule snapshots. This validation is currently done in the rules store right before persistence, so bad filter expression won't be detected till before the rule is persisted. By performing filter validation during construction, this can fail early when bad filter expression is detected.
=> Validate filter during snapshot construction

aggregation/id.go, aggregation/type.go, metadata/metadata.go, metadata/metadata_test.go, op/applied/type.go, op/applied/type_test.go, op/type.go, op/type_test.go, policy/storage_policy.go
cc @cw9 
This PR adds metric and pipeline metadata so we can send metadata alongside metrics to downstream services.
=> Add metric and pipeline metadata

rules/models/mapping.go, rules/models/mapping_test.go, rules/models/rollup.go, rules/models/rollup_test.go
When a number of structs that were floating around the m3 repos were consolidated here these two were left out. Moving them here so they are easily accessible.
=> add mapping rule and rollup rule history structs

op/applied/type.go, op/applied/type_test.go
This PR makes the `SubPipeline` API takes a start index and an end index.
=> More flexible SubPipeline API

errors/errors.go, glide.lock, glide.yaml, rules/store/kv/store.go, rules/store/kv/store_test.go
This PR introduces a new common error type to `StaleDataError`. This is returned by the rule store when a `WriteRuleSet` call fails because of some conditional failure.
=> add stale data error for conditional failures

aggregation/id_compress.go, aggregation/id_compress_test.go, metadata/metadata.go, metadata/metadata_test.go, metric/unaggregated/types.go
cc @cw9 @jeromefroe
This PR adds a few auxiliary functions and type definitions including `MustDecompress`, `DefaultStagedMetadata(s)` and `{Counter/Timer/Gauge}WithMetadatas`.
=> Add a few auxiliary functions and type definitions

errors/errors.go, rules/mapping.go, rules/rollup.go, rules/ruleset.go, rules/ruleset_test.go, rules/validator/validator.go, rules/validator/validator_test.go
We have previously introduced a `RuleSetChanges` struct. This PR adds a public method to the `MutableRuleSet` interface which takes a `RuleSetChanges` object as an argument and applies all the changes.
=> Add ApplyChanges function to mutable ruleset interface

rules/mapping.go, rules/mapping_test.go, rules/rollup.go, rules/rollup_test.go
cc @cw9  @jeromefroe 
This PR allows tombstoned rules to have empty targets and storage policies.
=> Allow tombstoned rules to have empty targets and storage policies

aggregation/id.go, aggregation/id_test.go, aggregation/type.go, metadata/metadata.go, metadata/metadata_test.go, pipeline/type.go, pipeline/type_test.go, policy/storage_policy.go
This PR adds the `VersionedMetadatas` struct and ability to marshal and unmarshal it in JSON format.
=> Allow marshaling and unmarshaling versioned metadatas as JSON

encoding/migration/unaggregated_iterator.go, encoding/migration/unaggregated_iterator_test.go
This PR ensures that closing a migration iterator will close the inner iterators.
=> Closing migration iterator should close inner iterators

rules/validator/config.go, rules/validator/config_test.go
cc @cw9 @jeromefroe @jskelcy 
This PR makes some of the override configuration fields optional for validation purposes.
=> Make override fields optional

metadata/metadata.go, metadata/metadata_test.go, rules/active_ruleset.go, rules/active_ruleset_test.go
This PR ensures that the pipeline list is always non empty for existing IDs even there are no mapping rule matches as we currently do not drop existing IDs even when there are no rule matches.
=> Ensure the pipelines are non-empty for existing IDs

aggregation/type.go, aggregation/type_config_test.go, aggregation/type_test.go, pipeline/type_test.go
cc @jskelcy @cw9 
This PR unmarshals aggregation types from YAML as lists.
=> Unmarshal aggregation types from YAML as lists

matcher/config.go, matcher/namespaces.go, matcher/ruleset.go, matcher/ruleset_test.go, rules/active_ruleset.go, rules/active_ruleset_test.go, rules/options.go, rules/ruleset.go, rules/ruleset_test.go, rules/validator/config.go, rules/validator/options.go, rules/validator/validator.go, rules/validator/validator_test.go
This PR adds ability to disallow multiple aggregation types for certain metric types and for those metric types, do not filter the pipelines by aggregation types during reverse matching.
=> Add ability to disallow multiple aggregation types

transformation/binary.go, transformation/binary_test.go
This PR adds logic so that `perSecond` returns an empty datapoint if the computed derivative is negative. This is consistent with the graphite [perSecond](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.perSecond) function semantics as well as `rate` function semantics in prometheus.
=> perSecond returns empty datapoint for negative rate

errors/errors.go, rules/store/kv/store.go, rules/store/kv/store_test.go
m3metrics has a number of typed errors that are returned so downstream applications can conditionally check them. When using the rules store a special type is now returned if the value is not found in KV. KV is the only implementation of the rules store currently.
=> Return a typed error when rules store value not found.
